export const INTERNAL_ERROR_MESSAGE = 'An unexpected error occurred.';

export const ERROR_CODES = {
  INTERNAL: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_REQUEST: 'INVALID_REQUEST',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  QUEUE_FULL: 'QUEUE_FULL',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  CORS_DENIED: 'CORS_DENIED',
  SERVER_SHUTTING_DOWN: 'SERVER_SHUTTING_DOWN',
} as const;

export const DEFAULT_ERROR_CODE_BY_STATUS: Readonly<Record<number, string>> = {
  404: ERROR_CODES.NOT_FOUND,
  429: ERROR_CODES.RATE_LIMIT_EXCEEDED,
};
